name: Update Backend on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  update-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into Raspberry Pi and Update Backend
        run: |
          sshpass -p "${{ secrets.RASP_PI_PSW }}" \
            ssh -o StrictHostKeyChecking=no romann@90.0.103.81 \
            'cd /var/www/canarn/server/server ; sudo git pull ; sudo systemctl restart canarn-backend'
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
